name: flutter_async_utils
description: Utilities for dealing with stream subscriptions and asynchronous
  tasks in flutter widgets.
version: 1.0.0
homepage: https://github.com/hpoul/flutter_async_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
