name: hooks_async_utils
description: Hook based async task util.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.20.5 <1.0.0"
  flutter_async_utils: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^4.0.0
