name: flutter_async_utils
description: Utilities for dealing with stream subscriptions and asynchronous
  tasks in flutter widgets.
version: 1.1.0
homepage: https://github.com/hpoul/flutter_async_utils

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
